#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBR_AI.DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OCX_DBR_DEV")]
	public partial class ParametersDataModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertocx_param_resource_calendar(ocx_param_resource_calendar instance);
    partial void Updateocx_param_resource_calendar(ocx_param_resource_calendar instance);
    partial void Deleteocx_param_resource_calendar(ocx_param_resource_calendar instance);
    partial void Insertvw_ocx_param_resource_calendar_edit(vw_ocx_param_resource_calendar_edit instance);
    partial void Updatevw_ocx_param_resource_calendar_edit(vw_ocx_param_resource_calendar_edit instance);
    partial void Deletevw_ocx_param_resource_calendar_edit(vw_ocx_param_resource_calendar_edit instance);
    partial void Insertocx_param_scheduled_resource(ocx_param_scheduled_resource instance);
    partial void Updateocx_param_scheduled_resource(ocx_param_scheduled_resource instance);
    partial void Deleteocx_param_scheduled_resource(ocx_param_scheduled_resource instance);
    partial void Insertvw_ocx_param_scheduled_resource_edit(vw_ocx_param_scheduled_resource_edit instance);
    partial void Updatevw_ocx_param_scheduled_resource_edit(vw_ocx_param_scheduled_resource_edit instance);
    partial void Deletevw_ocx_param_scheduled_resource_edit(vw_ocx_param_scheduled_resource_edit instance);
    #endregion
		
		public ParametersDataModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ParametersDataModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ParametersDataModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ParametersDataModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ocx_param_resource_calendar> ocx_param_resource_calendars
		{
			get
			{
				return this.GetTable<ocx_param_resource_calendar>();
			}
		}
		
		public System.Data.Linq.Table<vw_ocx_param_resource_calendar_edit> vw_ocx_param_resource_calendar_edits
		{
			get
			{
				return this.GetTable<vw_ocx_param_resource_calendar_edit>();
			}
		}
		
		public System.Data.Linq.Table<ocx_param_scheduled_resource> ocx_param_scheduled_resources
		{
			get
			{
				return this.GetTable<ocx_param_scheduled_resource>();
			}
		}
		
		public System.Data.Linq.Table<vw_ocx_param_scheduled_resource_edit> vw_ocx_param_scheduled_resource_edits
		{
			get
			{
				return this.GetTable<vw_ocx_param_scheduled_resource_edit>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="pub.ocx_param_resource_calendar")]
	public partial class ocx_param_resource_calendar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _dates;
		
		private System.Nullable<long> _working_hours;
		
		private System.Nullable<bool> _is_off;
		
		private string _day_of_week;
		
		private string _resource;
		
		private System.Nullable<bool> _is_customised;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndatesChanging(System.DateTime value);
    partial void OndatesChanged();
    partial void Onworking_hoursChanging(System.Nullable<long> value);
    partial void Onworking_hoursChanged();
    partial void Onis_offChanging(System.Nullable<bool> value);
    partial void Onis_offChanged();
    partial void Onday_of_weekChanging(string value);
    partial void Onday_of_weekChanged();
    partial void OnresourceChanging(string value);
    partial void OnresourceChanged();
    partial void Onis_customisedChanging(System.Nullable<bool> value);
    partial void Onis_customisedChanged();
    #endregion
		
		public ocx_param_resource_calendar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dates", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime dates
		{
			get
			{
				return this._dates;
			}
			set
			{
				if ((this._dates != value))
				{
					this.OndatesChanging(value);
					this.SendPropertyChanging();
					this._dates = value;
					this.SendPropertyChanged("dates");
					this.OndatesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_working_hours", DbType="BigInt")]
		public System.Nullable<long> working_hours
		{
			get
			{
				return this._working_hours;
			}
			set
			{
				if ((this._working_hours != value))
				{
					this.Onworking_hoursChanging(value);
					this.SendPropertyChanging();
					this._working_hours = value;
					this.SendPropertyChanged("working_hours");
					this.Onworking_hoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_off", DbType="Bit")]
		public System.Nullable<bool> is_off
		{
			get
			{
				return this._is_off;
			}
			set
			{
				if ((this._is_off != value))
				{
					this.Onis_offChanging(value);
					this.SendPropertyChanging();
					this._is_off = value;
					this.SendPropertyChanged("is_off");
					this.Onis_offChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_day_of_week", DbType="VarChar(10)")]
		public string day_of_week
		{
			get
			{
				return this._day_of_week;
			}
			set
			{
				if ((this._day_of_week != value))
				{
					this.Onday_of_weekChanging(value);
					this.SendPropertyChanging();
					this._day_of_week = value;
					this.SendPropertyChanged("day_of_week");
					this.Onday_of_weekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resource", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string resource
		{
			get
			{
				return this._resource;
			}
			set
			{
				if ((this._resource != value))
				{
					this.OnresourceChanging(value);
					this.SendPropertyChanging();
					this._resource = value;
					this.SendPropertyChanged("resource");
					this.OnresourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_customised", DbType="Bit")]
		public System.Nullable<bool> is_customised
		{
			get
			{
				return this._is_customised;
			}
			set
			{
				if ((this._is_customised != value))
				{
					this.Onis_customisedChanging(value);
					this.SendPropertyChanging();
					this._is_customised = value;
					this.SendPropertyChanged("is_customised");
					this.Onis_customisedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="asp.vw_ocx_param_resource_calendar_edit")]
	public partial class vw_ocx_param_resource_calendar_edit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ASP_KEY;
		
		private System.DateTime _dates;
		
		private System.Nullable<int> _calendarYear;
		
		private System.Nullable<int> _calendarMonth;
		
		private System.Nullable<int> _calendarDay;
		
		private System.Nullable<long> _working_hours;
		
		private System.Nullable<bool> _is_off;
		
		private string _day_of_week;
		
		private string _resource;
		
		private System.Nullable<bool> _is_customised;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnASP_KEYChanging(string value);
    partial void OnASP_KEYChanged();
    partial void OndatesChanging(System.DateTime value);
    partial void OndatesChanged();
    partial void OncalendarYearChanging(System.Nullable<int> value);
    partial void OncalendarYearChanged();
    partial void OncalendarMonthChanging(System.Nullable<int> value);
    partial void OncalendarMonthChanged();
    partial void OncalendarDayChanging(System.Nullable<int> value);
    partial void OncalendarDayChanged();
    partial void Onworking_hoursChanging(System.Nullable<long> value);
    partial void Onworking_hoursChanged();
    partial void Onis_offChanging(System.Nullable<bool> value);
    partial void Onis_offChanged();
    partial void Onday_of_weekChanging(string value);
    partial void Onday_of_weekChanged();
    partial void OnresourceChanging(string value);
    partial void OnresourceChanged();
    partial void Onis_customisedChanging(System.Nullable<bool> value);
    partial void Onis_customisedChanged();
    #endregion
		
		public vw_ocx_param_resource_calendar_edit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASP_KEY", DbType="VarChar(61)", IsPrimaryKey=true)]
		public string ASP_KEY
		{
			get
			{
				return this._ASP_KEY;
			}
			set
			{
				if ((this._ASP_KEY != value))
				{
					this.OnASP_KEYChanging(value);
					this.SendPropertyChanging();
					this._ASP_KEY = value;
					this.SendPropertyChanged("ASP_KEY");
					this.OnASP_KEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dates", DbType="Date NOT NULL")]
		public System.DateTime dates
		{
			get
			{
				return this._dates;
			}
			set
			{
				if ((this._dates != value))
				{
					this.OndatesChanging(value);
					this.SendPropertyChanging();
					this._dates = value;
					this.SendPropertyChanged("dates");
					this.OndatesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calendarYear", DbType="Int")]
		public System.Nullable<int> calendarYear
		{
			get
			{
				return this._calendarYear;
			}
			set
			{
				if ((this._calendarYear != value))
				{
					this.OncalendarYearChanging(value);
					this.SendPropertyChanging();
					this._calendarYear = value;
					this.SendPropertyChanged("calendarYear");
					this.OncalendarYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calendarMonth", DbType="Int")]
		public System.Nullable<int> calendarMonth
		{
			get
			{
				return this._calendarMonth;
			}
			set
			{
				if ((this._calendarMonth != value))
				{
					this.OncalendarMonthChanging(value);
					this.SendPropertyChanging();
					this._calendarMonth = value;
					this.SendPropertyChanged("calendarMonth");
					this.OncalendarMonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calendarDay", DbType="Int")]
		public System.Nullable<int> calendarDay
		{
			get
			{
				return this._calendarDay;
			}
			set
			{
				if ((this._calendarDay != value))
				{
					this.OncalendarDayChanging(value);
					this.SendPropertyChanging();
					this._calendarDay = value;
					this.SendPropertyChanged("calendarDay");
					this.OncalendarDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_working_hours", DbType="BigInt")]
		public System.Nullable<long> working_hours
		{
			get
			{
				return this._working_hours;
			}
			set
			{
				if ((this._working_hours != value))
				{
					this.Onworking_hoursChanging(value);
					this.SendPropertyChanging();
					this._working_hours = value;
					this.SendPropertyChanged("working_hours");
					this.Onworking_hoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_off", DbType="Bit")]
		public System.Nullable<bool> is_off
		{
			get
			{
				return this._is_off;
			}
			set
			{
				if ((this._is_off != value))
				{
					this.Onis_offChanging(value);
					this.SendPropertyChanging();
					this._is_off = value;
					this.SendPropertyChanged("is_off");
					this.Onis_offChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_day_of_week", DbType="VarChar(10)")]
		public string day_of_week
		{
			get
			{
				return this._day_of_week;
			}
			set
			{
				if ((this._day_of_week != value))
				{
					this.Onday_of_weekChanging(value);
					this.SendPropertyChanging();
					this._day_of_week = value;
					this.SendPropertyChanged("day_of_week");
					this.Onday_of_weekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resource", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string resource
		{
			get
			{
				return this._resource;
			}
			set
			{
				if ((this._resource != value))
				{
					this.OnresourceChanging(value);
					this.SendPropertyChanging();
					this._resource = value;
					this.SendPropertyChanged("resource");
					this.OnresourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_customised", DbType="Bit")]
		public System.Nullable<bool> is_customised
		{
			get
			{
				return this._is_customised;
			}
			set
			{
				if ((this._is_customised != value))
				{
					this.Onis_customisedChanging(value);
					this.SendPropertyChanging();
					this._is_customised = value;
					this.SendPropertyChanged("is_customised");
					this.Onis_customisedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="pub.ocx_param_scheduled_resource")]
	public partial class ocx_param_scheduled_resource : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _resource_group;
		
		private System.Nullable<int> _capacity;
		
		private System.Nullable<bool> _is_constraint;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Onresource_groupChanging(string value);
    partial void Onresource_groupChanged();
    partial void OncapacityChanging(System.Nullable<int> value);
    partial void OncapacityChanged();
    partial void Onis_constraintChanging(System.Nullable<bool> value);
    partial void Onis_constraintChanged();
    #endregion
		
		public ocx_param_scheduled_resource()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resource_group", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string resource_group
		{
			get
			{
				return this._resource_group;
			}
			set
			{
				if ((this._resource_group != value))
				{
					this.Onresource_groupChanging(value);
					this.SendPropertyChanging();
					this._resource_group = value;
					this.SendPropertyChanged("resource_group");
					this.Onresource_groupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacity", DbType="Int")]
		public System.Nullable<int> capacity
		{
			get
			{
				return this._capacity;
			}
			set
			{
				if ((this._capacity != value))
				{
					this.OncapacityChanging(value);
					this.SendPropertyChanging();
					this._capacity = value;
					this.SendPropertyChanged("capacity");
					this.OncapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_constraint", DbType="Bit")]
		public System.Nullable<bool> is_constraint
		{
			get
			{
				return this._is_constraint;
			}
			set
			{
				if ((this._is_constraint != value))
				{
					this.Onis_constraintChanging(value);
					this.SendPropertyChanging();
					this._is_constraint = value;
					this.SendPropertyChanged("is_constraint");
					this.Onis_constraintChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="asp.vw_ocx_param_scheduled_resource_edit")]
	public partial class vw_ocx_param_scheduled_resource_edit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ASP_KEY;
		
		private System.Nullable<long> _id;
		
		private string _resource_group;
		
		private System.Nullable<int> _capacity;
		
		private System.Nullable<bool> _is_constraint;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnASP_KEYChanging(string value);
    partial void OnASP_KEYChanged();
    partial void OnidChanging(System.Nullable<long> value);
    partial void OnidChanged();
    partial void Onresource_groupChanging(string value);
    partial void Onresource_groupChanged();
    partial void OncapacityChanging(System.Nullable<int> value);
    partial void OncapacityChanged();
    partial void Onis_constraintChanging(System.Nullable<bool> value);
    partial void Onis_constraintChanged();
    #endregion
		
		public vw_ocx_param_scheduled_resource_edit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASP_KEY", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ASP_KEY
		{
			get
			{
				return this._ASP_KEY;
			}
			set
			{
				if ((this._ASP_KEY != value))
				{
					this.OnASP_KEYChanging(value);
					this.SendPropertyChanging();
					this._ASP_KEY = value;
					this.SendPropertyChanged("ASP_KEY");
					this.OnASP_KEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt")]
		public System.Nullable<long> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resource_group", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string resource_group
		{
			get
			{
				return this._resource_group;
			}
			set
			{
				if ((this._resource_group != value))
				{
					this.Onresource_groupChanging(value);
					this.SendPropertyChanging();
					this._resource_group = value;
					this.SendPropertyChanged("resource_group");
					this.Onresource_groupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacity", DbType="Int")]
		public System.Nullable<int> capacity
		{
			get
			{
				return this._capacity;
			}
			set
			{
				if ((this._capacity != value))
				{
					this.OncapacityChanging(value);
					this.SendPropertyChanging();
					this._capacity = value;
					this.SendPropertyChanged("capacity");
					this.OncapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_constraint", DbType="Bit")]
		public System.Nullable<bool> is_constraint
		{
			get
			{
				return this._is_constraint;
			}
			set
			{
				if ((this._is_constraint != value))
				{
					this.Onis_constraintChanging(value);
					this.SendPropertyChanging();
					this._is_constraint = value;
					this.SendPropertyChanged("is_constraint");
					this.Onis_constraintChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
